gt_theta: 0.3
gamma: 0.999
ignore_dist_constraint: true
learning_rate: 7.77e-05
ent_coef: 0.01

lin_vel_min: -0.1
lin_vel_max: 0.5

lin_accl_min: -1
lin_accl_max: 1

phi_vel_min: -3.141592653589793 #  -pi/s
phi_vel_max: 3.141592653589793 #  pi/s

goal_tolerance_lin_vel: 0.05
goal_tolerance_phi: 0.2618 

phi_min: -1.0472 # - pi/3
phi_max: 1.0472 # pi/3

L: 0.25

delta_t: 0.1

max_steps: 20 # SMALLER THEN IN THE ORIGINAL.

stop_at_lin_constraint_violation: False
m_v: 0.1
m_d: 0.01

id_postfix: "_ncv_dense_reward_higher_lin_accl_phi_vel"
